introduction:
  title: Introduction

gettingStarted:
  title: Getting Started
  installing: Downloading and Installing
  creatingAnApplication: Creating an Application
  consoleExample: A Groovy Console Example
  ideSetup: Getting Set-up in an IDE
  conventionOverConfiguration: Convention over Configuration
  runningAnApplication: Running an application
  testingAnApplication: Testing an Application
  creatingArtefacts: Creating artefatcs

configuration:
  title: Configuration
  basicConfiguration: Basic Configuration
  logging: Logging
  environments: Environments
  versioning: Versioning
  dependencyResolution:
    title: Dependency Resolution
    configurationsAndDependencies: Configurations and Dependencies
    dependencyRepositories: Dependency Repositories
    debuggingResolution: Debugging Resolution
    inheritedDependencies: Inherited Dependencies
    dependencyReports: Dependency Reports
    pluginDependencies: Plugin JAR Dependencies
  projectDocumentation: Project Documentation
  compiler:
    title: Compiler
    sourceEncoding: Source Encoding
    sourceAndTargetLevels: Source and Target Levels
    debugInformation: Debug Information
    additionalSources: Additional Sources
    additionalResources: Additional Resources

theCommandLine:
  title: The Command Line
  creatingGantScripts: Creating Gant Scripts
  reusingGriffonScripts: Re-using Griffon scripts
  hookingIntoEvents: Hooking into Events
  customisingTheBuild: Customising the build
  commandToolsIntegration: Command Tools Integration
  theGriffonWrapper: The Griffon Wrapper
  commandLineOptions:
    title: Command Line Options
    verboseOutput: Verbose Output
    disableAstInjection: Disable AST Injection
    disableDefaultImports: Disable Default Imports
    disableConditionalLoggingInjection: Disable Conditional Logging Injection
    disableThreadingInjection: Disable Threading Injection
    defaultAnswerNonInteractiveMode: Default Answer in Non Interactive Mode
    forceArtifactUpgrades: Force Artifact Upgrades
    pluginInstallFailureStrategies: Plugin Install Failure Strategies
    defaultArtifactRespositorySearching: Default Artifact Repository for Searching
    defaultArtifactRespositoryCaching: Default Artifact Repository for Caching
    defaultArtifactRespositoryPublishing: Default Artifact Repository for Publishing
    disableAutomaticLocalRepoSync: Disable Automatic Local Repository Synchronization
  theGriffonShell:
    title: The Griffon Shell
    addingCommandHelp: Adding Command Help and Options

applicationOverview:
  title: Application Overview
  directoryStructure: Directory Structure
  theMvcPattern: 
    title: The MVC Pattern
    mvcGroupManager: MVCGroupManager
    mvcGroups: MVCGroups and Configuration
    configurationOptions: Configuration Options
  runtimeConfiguration:
    title: Runtime Configuration
    i18nableConfiguration: Internationalization Support
    externalConfiguration: External Configuration Support
  applicationLifecycle:
    title: Application Lifecycle
    initialize: Initialize
    startup: Startup
    ready: Ready
    shutdown: Shutdown
    stop: Stop
  applicationEvents:
    title: Application Events
    lifeCycleEvents: Life Cycle Events
    artifactEvents: Artifact Events
    miscellaneousEvents: Miscellaneous Events
    customEvents: Custom Events
    eventHandlers: Event Handlers
    customEventPublishers: Custom Event Publishers
  applicationFeatures:
    title: Application Features
    metadata: Metadata
    environment: Environment
    runningMode: Running Mode
    shutdownHandlers: Shutdown Handlers
    applicationPhase: Application Phase
    applicationLocale: Application Locale
    defaultImports: Default Imports
    startupArguments: Startup Arguments
    uncaughtExceptions: Uncaught Exceptions
  windowManager: WindowManager
  artifactApi:
    title: Artifact API
    evaluatingConventions: Evaluating Conventions
    addingDynamicMethods: Adding Dynamic Methods at Runtime
    artifactTypes: Artifact Types
  archetypes:
    title: Archetypes
    fancyExample: A Fancy Example
  platformSpecific:
    title: Platform Specific
    platformTweaks: Tweaks for a Particular Platform
    macosx: MacOSX
  managerConfiguration: Manager Configuration

modelsAndBinding:
  title: Models and Binding
  models: Models
  binding:
    title: Binding
    syntax: Syntax
    additionalProperties: Additional Properties

views:
  title: Views
  viewsAndSwing: Views and Swing
  specialNodes:
    title: Special Nodes
    application: Application
    container: Container
    widget: Widget
    bean: Bean
    noparent: Noparent
    root: Root
    metaComponent: MetaComponent

controllersAndServices:
  title: Controllers and Services
  controllers:
    title: Controllers
    actionsAndThreads: Actions and Threads
    actionManager: The Action Manager
  services:
    title: Services
    serviceLifecycle: Service Lifecycle
    serviceConfiguration: Configuration DSL

threading:
  title: Threading
  swingThreading:
    title: Swing Threading
    edt: Synchronous Calls
    doLater: Asynchronous Calls
    doOutside: Outside Calls
  toolkitAgnosticThreading:
    title: Toolkit-agnostic Threading
    sync: Synchronous Calls
    async: Asynchronous Calls
    outside: Outside Calls
    additionalMethods: Additional Methods
  annotationBasedThreading: Annotation Based Threading

internationalization:
  title: Internationalization
  messageSource: The Messsage Source
  i18nConfiguration: Configuration
  i18nTransform: Injecting Message Source Behavior

resourceManagement:
  title: Resource Management
  locatingClasspathResources: Locating Classpath Resources
  resourceResolver: Resolving Configured Resources
  resourceConfiguration: Configuration
  injectedResources: Automatically Injected Resources
  resourceTransform: Injecting Resource Resolution Behavior
  propertyEditors: Property Editors

testing:
  title: Testing
  unitTesting: Unit Testing
  integrationTesting: Integration Testing
  mocking:
    title: Mocking
    mockGriffonApplication: MockGriffonApplication

packaging:
  title: Packaging and Deployment
  zip: Zip
  jar: Jar
  webstart: Webstart
  applet: Applet
  additionalPackagingModes: Additional modes
  customManifestEntries: Custom Manifest Entries

plugins:
  title: Plugins
  creatingPlugins: Creating and Installing Plugins
  artifactRepositories: Artifact Repositories
  pluginStructure: Understanding a Plugins Structure
  providingArtefacts: Providing Basic Artefacts
  hookingIntoBuildEvents: Hooking into Build Events
  addons: Addons
  pluginOrder: Understanding Plugin Order
  cliDependencies: CLI Dependencies

tips:
  title: Tips and Tricks
  artifactConventions: Using Artifact Conventions to your Advantage
  nonGroovyArtifacts: Dealing with Non-Groovy Artifacts
  externalizedViews:
    title: Externalizing Views
    matisse: NetBeans Matisse
    abeille: Abeille Forms Designer
    xml: XML
  javaBindings: Creating Bindings in Java

contributing: 
  title: Contributing to Griffon
  issues: Report Issues in JIRA
  build: Build From Source and Run Tests
  patchesCore: Submit Patches to Griffon Core
